name: Build and Publish Container Image

on:
  schedule:
    - cron: '25 20 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
  #  branches: [ "main" ]


env:
  # Use docker.io for Docker Hub || ghcr.io for Github ...
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 1.7.1
  TEST_TAG: ${{ github.repository }}:test
  VERSION_TAG: ${{ github.repository }}
  #:${{VERSION}}
  LATEST_TAG: ${{ github.repository }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      ## QEMU allowsfor the building for different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{env.TEST_TAG}}, ${{env.LATEST_TAG}}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: bretfisher/allhands22
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          #platform options
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          #platforms: linux/amd64
          ##push the image to the registry ONLY IF it is not a pull request  (when the pull request is merged then it will push to the registry)
          #push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          #push: true
          ##when using the buildkit layers can be cached to speed future builds
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          tags: ${{ env.LATEST_TAG }}, ${{ env.VERSION_TAG }}:${{env.VERSION}}